const editorStyleDependency = (attributes) => {
	const {
		uniqueId,
		columnWidth,
		columnBg,
		columnBgImage,
		columnBorder,
		columnZIndex,
		columnPadding,
		columnMargin,
		columnBorderWidth,
		columnBorderRadius,
		columnBoxShadowEnable,
		columnBoxShadow,
		columnVisibilityHideDesktop,
		columnVisibilityHideTablet,
		columnVisibilityHideMobile,
		columnBgImageHover,
		columnBoxShadowEnableHover,
		columnBoxShadowHover,
		columnOverlayType,
		columnOverlayBg,
		columnOverlayOpacity,
		columnOverlayBlandMode,
		columnOverlayTypeHover,
		columnOverlayOpacityHover,
		columnOverlayBlandModeHover,
		columnBorderWidthHover,
		columnBorderRadiusHover,
		parentColumnGap,
		parentContainerFlexDirection,
	} = attributes;
	const dependency = [
		uniqueId,
		columnWidth,
		columnBg,
		columnBgImage,
		columnBorder,
		columnZIndex,
		columnPadding,
		columnMargin,
		columnBorderWidth,
		columnBorderRadius,
		columnBoxShadowEnable,
		columnBoxShadow,
		columnVisibilityHideDesktop,
		columnVisibilityHideTablet,
		columnVisibilityHideMobile,
		columnBgImageHover,
		columnBoxShadowEnableHover,
		columnBoxShadowHover,
		columnOverlayType,
		columnOverlayBg,
		columnOverlayOpacity,
		columnOverlayBlandMode,
		columnOverlayTypeHover,
		columnOverlayOpacityHover,
		columnOverlayBlandModeHover,
		columnBorderWidthHover,
		columnBorderRadiusHover,
		parentColumnGap,
		parentContainerFlexDirection,
	];
	return dependency;
};
export default editorStyleDependency;
