// const fontAwesome = {
// 	Arrows: [
// 		'fa fa-angle-double-down',
// 		'fa fa-angle-double-left',
// 		'fa fa-angle-double-right',
// 		'fa fa-angle-double-up',
// 		'fa fa-times',
// 		'fa fa-angle-down',
// 		'fa fa-angle-left',
// 		'fa fa-angle-right',
// 		'fa fa-angle-up',
// 		'fa fa-window-close',
// 		'fa fa-arrow-circle-down',
// 		'fa fa-arrow-circle-left',
// 		'fa fa-arrow-circle-right',
// 		'fa fa-window-close-o',
// 		'fa fa-arrow-circle-up',
// 		'fa fa-arrow-down',
// 		'fa fa-arrow-left',
// 		'fa fa-arrow-right',
// 		'fa fa-arrow-up',
// 		'fa fa-times-circle',
// 		'fa fa-arrows',
// 		'fa fa-arrows-alt',
// 		'fa fa-arrows-h',
// 		'fa fa-arrows-v',
// 		'fa fa-caret-down',
// 		'fa fa-caret-left',
// 		'fa fa-caret-right',
// 		'fa fa-caret-up',
// 		'fa fa-chevron-circle-down',
// 		'fa fa-chevron-circle-left',
// 		'fa fa-chevron-circle-right',
// 		'fa fa-chevron-circle-up',
// 		'fa fa-chevron-down',
// 		'fa fa-chevron-left',
// 		'fa fa-chevron-right',
// 		'fa fa-chevron-up',
// 		'fa fa-hand-o-down',
// 		'fa fa-hand-o-left',
// 		'fa fa-hand-o-right',
// 		'fa fa-hand-o-up',
// 		'fa fa-long-arrow-down',
// 		'fa fa-long-arrow-left',
// 		'fa fa-long-arrow-right',
// 		'fa fa-long-arrow-up',
// 		'fa fa-arrow-circle-o-down',
// 		'fa fa-arrow-circle-o-left',
// 		'fa fa-arrow-circle-o-right',
// 		'fa fa-arrow-circle-o-up',
// 		'fa fa-caret-square-o-down',
// 		'fa fa-caret-square-o-left',
// 		'fa fa-caret-square-o-right',
// 		'fa fa-caret-square-o-up',
// 		'fa fa-exchange',
// 		'fa fa-toggle-down',
// 		'fa fa-toggle-left',
// 		'fa fa-toggle-right',
// 		'fa fa-toggle-up',
// 	],
// 	Social: [
// 		'fa fa-facebook',
// 		'fa fa-facebook-square',
// 		'fa fa-twitter',
// 		'fa fa-twitter-square',
// 		'fa fa-instagram',
// 		'fa fa-linkedin',
// 		'fa fa-github',
// 		'fa fa-wordpress',
// 		'fa fa-whatsapp',
// 		'fa fa-behance',
// 		'fa fa-google-plus',
// 		'fa fa-google-plus-square',
// 		'fa fa-pinterest',
// 	],
// 	Communication: [
// 		'fa fa-address-book',
// 		'fa fa-address-card',
// 		'fa fa-bell',
// 		'fa fa-bell-slash',
// 		'fa fa-bluetooth',
// 		'fa fa-bullhorn',
// 		'fa fa-comment',
// 		'fa fa-comment-o',
// 		'fa fa-comments',
// 		'fa fa-comments-o',
// 		'fa fa-envelope',
// 		'fa fa-envelope-o',
// 		'fa fa-envelope-square',
// 		'fa fa-fax',
// 		'fa fa-inbox',
// 		'fa fa-language',
// 		'fa fa-microphone',
// 		'fa fa-microphone-slash',
// 		'fa fa-mobile',
// 		'fa fa-paper-plane',
// 		'fa fa-paper-plane-o',
// 		'fa fa-phone',
// 		'fa fa-phone-square',
// 		'fa fa-rss',
// 		'fa fa-rss-square',
// 		'fa fa-tty',
// 		'fa fa-wifi',
// 	],
// 	Accessibility: [
// 		'fa fa-american-sign-language-interpreting',
// 		'fa fa-assistive-listening-systems',
// 		'fa fa-audio-description',
// 		'fa fa-blind',
// 		'fa fa-braille',
// 		'fa fa-deaf',
// 		'fa fa-low-vision',
// 		'fa fa-question-circle',
// 		'fa fa-sign-language',
// 		'fa fa-tty',
// 		'fa fa-universal-access',
// 		'fa fa-wheelchair',
// 	],
// 	'Audio & Video': [
// 		'fa fa-backward',
// 		'fa fa-circle',
// 		'fa fa-compress',
// 		'fa fa-eject',
// 		'fa fa-expand',
// 		'fa fa-fast-backward',
// 		'fa fa-fast-forward',
// 		'fa fa-file-audio-o',
// 		'fa fa-file-video-o',
// 		'fa fa-film',
// 		'fa fa-forward',
// 		'fa fa-headphones',
// 		'fa fa-microphone',
// 		'fa fa-microphone-slash',
// 		'fa fa-music',
// 		'fa fa-pause',
// 		'fa fa-pause-circle',
// 		'fa fa-play',
// 		'fa fa-play-circle',
// 		'fa fa-random',
// 		'fa fa-step-backward',
// 		'fa fa-step-forward',
// 		'fa fa-stop',
// 		'fa fa-stop-circle',
// 		'fa fa-video-camera',
// 		'fa fa-volume-down',
// 		'fa fa-volume-off',
// 		'fa fa-volume-up',
// 		'fa fa-youtube',
// 	],
// 	Business: [
// 		'fa fa-address-book',
// 		'fa fa-address-card',
// 		'fa fa-archive',
// 		'fa fa-balance-scale',
// 		'fa fa-birthday-cake',
// 		'fa fa-book',
// 		'fa fa-briefcase',
// 		'fa fa-building',
// 		'fa fa-bullhorn',
// 		'fa fa-bullseye',
// 		'fa fa-calculator',
// 		'fa fa-calendar',
// 		'fa fa-certificate',
// 		'fa fa-clipboard',
// 		'fa fa-coffee',
// 		'fa fa-columns',
// 		'fa fa-compass',
// 		'fa fa-copy',
// 		'fa fa-copyright',
// 		'fa fa-cut',
// 		'fa fa-edit',
// 		'fa fa-envelope',
// 		'fa fa-envelope-open',
// 		'fa fa-envelope-square',
// 		'fa fa-eraser',
// 		'fa fa-fax',
// 		'fa fa-file',
// 		'fa fa-file-text',
// 		'fa fa-folder',
// 		'fa fa-folder-open',
// 		'fa fa-globe',
// 		'fa fa-industry',
// 		'fa fa-paperclip',
// 		'fa fa-paste',
// 		'fa fa-pencil-square',
// 		'fa fa-percent',
// 		'fa fa-phone',
// 		'fa fa-phone-square',
// 		'fa fa-registered',
// 		'fa fa-save',
// 		'fa fa-sitemap',
// 		'fa fa-sticky-note',
// 		'fa fa-suitcase',
// 		'fa fa-table',
// 		'fa fa-tag',
// 		'fa fa-tags',
// 		'fa fa-tasks',
// 		'fa fa-thumb-tack',
// 		'fa fa-trademark',
// 	],
// 	Code: [
// 		'fa fa-archive',
// 		'fa fa-barcode',
// 		'fa fa-bug',
// 		'fa fa-code',
// 		'fa fa-code-fork',
// 		'fa fa-coffee',
// 		'fa fa-file',
// 		'fa fa-file-text',
// 		'fa fa-filter',
// 		'fa fa-fire-extinguisher',
// 		'fa fa-folder',
// 		'fa fa-folder-open',
// 		'fa fa-microchip',
// 		'fa fa-qrcode',
// 		'fa fa-shield',
// 		'fa fa-sitemap',
// 		'fa fa-terminal',
// 		'fa fa-user-secret',
// 		'fa fa-window-close',
// 		'fa fa-window-maximize',
// 		'fa fa-window-minimize',
// 		'fa fa-window-restore',
// 	],
// 	Computers: [
// 		'fa fa-desktop',
// 		'fa fa-download',
// 		'fa fa-hdd-o',
// 		'fa fa-headphones',
// 		'fa fa-laptop',
// 		'fa fa-microchip',
// 		'fa fa-mobile',
// 		'fa fa-plug',
// 		'fa fa-power-off',
// 		'fa fa-print',
// 		'fa fa-save',
// 		'fa fa-server',
// 		'fa fa-tablet',
// 		'fa fa-tv',
// 		'fa fa-upload',
// 	],
// 	Currency: [
// 		'fa fa-bitcoin',
// 		'fa fa-btc',
// 		'fa fa-dollar',
// 		'fa fa-eur',
// 		'fa fa-gbp',
// 		'fa fa-gg',
// 		'fa fa-ils',
// 		'fa fa-inr',
// 		'fa fa-jpy',
// 		'fa fa-krw',
// 		'fa fa-money',
// 		'fa fa-rub',
// 		'fa fa-try',
// 		'fa fa-usd',
// 	],
// 	'Date & Time': [
// 		'fa fa-bell',
// 		'fa fa-bell-slash',
// 		'fa fa-calendar',
// 		'fa fa-clock-o',
// 		'fa fa-hourglass',
// 		'fa fa-hourglass-end',
// 		'fa fa-hourglass-half',
// 		'fa fa-hourglass-start',
// 	],
// 	Design: [
// 		'fa fa-adjust',
// 		'fa fa-clone',
// 		'fa fa-copy',
// 		'fa fa-crop',
// 		'fa fa-crosshairs',
// 		'fa fa-cut',
// 		'fa fa-edit',
// 		'fa fa-eraser',
// 		'fa fa-eye',
// 		'fa fa-eye-slash',
// 		'fa fa-object-group',
// 		'fa fa-object-ungroup',
// 		'fa fa-paint-brush',
// 		'fa fa-paste',
// 		'fa fa-pencil',
// 		'fa fa-save',
// 		'fa fa-tint',
// 	],
// 	Editors: [
// 		'fa fa-align-center',
// 		'fa fa-align-justify',
// 		'fa fa-align-left',
// 		'fa fa-align-right',
// 		'fa fa-bold',
// 		'fa fa-clipboard',
// 		'fa fa-columns',
// 		'fa fa-copy',
// 		'fa fa-cut',
// 		'fa fa-edit',
// 		'fa fa-eraser',
// 		'fa fa-file',
// 		'fa fa-file-text',
// 		'fa fa-font',
// 		'fa fa-header',
// 		'fa fa-indent',
// 		'fa fa-italic',
// 		'fa fa-link',
// 		'fa fa-list',
// 		'fa fa-list-alt',
// 		'fa fa-list-ol',
// 		'fa fa-list-ul',
// 		'fa fa-outdent',
// 		'fa fa-paperclip',
// 		'fa fa-paragraph',
// 		'fa fa-paste',
// 		'fa fa-pencil',
// 		'fa fa-print',
// 		'fa fa-quote-left',
// 		'fa fa-quote-right',
// 		'fa fa-reply',
// 		'fa fa-reply-all',
// 		'fa fa-share',
// 		'fa fa-strikethrough',
// 		'fa fa-subscript',
// 		'fa fa-superscript',
// 		'fa fa-table',
// 		'fa fa-tasks',
// 		'fa fa-text-height',
// 		'fa fa-text-width',
// 		'fa fa-th',
// 		'fa fa-th-large',
// 		'fa fa-th-list',
// 		'fa fa-trash',
// 		'fa fa-underline',
// 		'fa fa-undo',
// 	],
// 	Files: [
// 		'fa fa-archive',
// 		'fa fa-clone',
// 		'fa fa-copy',
// 		'fa fa-cut',
// 		'fa fa-file',
// 		'fa fa-file-text',
// 		'fa fa-file-archive-o',
// 		'fa fa-file-audio-o',
// 		'fa fa-file-code-o',
// 		'fa fa-file-excel-o',
// 		'fa fa-file-image-o',
// 		'fa fa-file-pdf-o',
// 		'fa fa-file-powerpoint-o',
// 		'fa fa-file-video-o',
// 		'fa fa-file-word-o',
// 		'fa fa-folder',
// 		'fa fa-folder-open',
// 		'fa fa-paste',
// 		'fa fa-save',
// 		'fa fa-sticky-note',
// 	],
// 	Genders: [
// 		'fa fa-genderless',
// 		'fa fa-mars',
// 		'fa fa-mars-double',
// 		'fa fa-mars-stroke',
// 		'fa fa-mars-stroke-h',
// 		'fa fa-mars-stroke-v',
// 		'fa fa-mercury',
// 		'fa fa-neuter',
// 		'fa fa-transgender',
// 		'fa fa-transgender-alt',
// 		'fa fa-venus',
// 		'fa fa-venus-double',
// 		'fa fa-venus-mars',
// 	],
// 	Hands: [
// 		'fa fa-hand-lizard-o',
// 		'fa fa-hand-rock-o',
// 		'fa fa-hand-pointer-o',
// 		'fa fa-hand-paper-o',
// 		'fa fa-hand-o-right',
// 		'fa fa-hand-o-left',
// 		'fa fa-hand-o-up',
// 		'fa fa-hand-o-down',
// 		'fa fa-thumbs-down',
// 		'fa fa-thumbs-up',
// 		'fa fa-hand-scissors-o',
// 		'fa fa-hand-spock-o',
// 		'fa fa-thumbs-o-up',
// 		'fa fa-thumbs-o-down',
// 	],
// 	Health: [
// 		'fa fa-ambulance',
// 		'fa fa-h-square',
// 		'fa fa-heart',
// 		'fa fa-heartbeat',
// 		'fa fa-medkit',
// 		'fa fa-hospital-o',
// 		'fa fa-plus-square',
// 		'fa fa-stethoscope',
// 		'fa fa-user-md',
// 		'fa fa-wheelchair',
// 	],
// 	Images: [
// 		'fa fa-adjust',
// 		'fa fa-bolt',
// 		'fa fa-camera',
// 		'fa fa-camera-retro',
// 		'fa fa-clone',
// 		'fa fa-compress',
// 		'fa fa-expand',
// 		'fa fa-eye',
// 		'fa fa-eye-slash',
// 		'fa fa-file-image-o',
// 		'fa fa-film',
// 		'fa fa-id-badge',
// 		'fa fa-id-card',
// 		'fa fa-image',
// 		'fa fa-sliders',
// 		'fa fa-tint',
// 	],
// 	Interfaces: [
// 		'fa fa-ban',
// 		'fa fa-barcode',
// 		'fa fa-bars',
// 		'fa fa-beer',
// 		'fa fa-bell',
// 		'fa fa-bell-slash',
// 		'fa fa-bug',
// 		'fa fa-bullhorn',
// 		'fa fa-bullseye',
// 		'fa fa-calculator',
// 		'fa fa-calendar',
// 		'fa fa-certificate',
// 		'fa fa-check',
// 		'fa fa-check-circle',
// 		'fa fa-check-square',
// 		'fa fa-circle',
// 		'fa fa-clipboard',
// 		'fa fa-clone',
// 		'fa fa-cloud',
// 		'fa fa-cloud-download',
// 		'fa fa-cloud-upload',
// 		'fa fa-coffee',
// 		'fa fa-cog',
// 		'fa fa-cogs',
// 		'fa fa-copy',
// 		'fa fa-cut',
// 		'fa fa-database',
// 		'fa fa-download',
// 		'fa fa-edit',
// 		'fa fa-ellipsis-h',
// 		'fa fa-ellipsis-v',
// 		'fa fa-envelope',
// 		'fa fa-envelope-open',
// 		'fa fa-eraser',
// 		'fa fa-exclamation',
// 		'fa fa-exclamation-circle',
// 		'fa fa-exclamation-triangle',
// 		'fa fa-external-link',
// 		'fa fa-external-link-square',
// 		'fa fa-eye',
// 		'fa fa-eye-slash',
// 		'fa fa-file',
// 		'fa fa-filter',
// 		'fa fa-flag',
// 		'fa fa-flag-checkered',
// 		'fa fa-folder',
// 		'fa fa-folder-open',
// 		'fa fa-hashtag',
// 		'fa fa-heart',
// 		'fa fa-history',
// 		'fa fa-home',
// 		'fa fa-i-cursor',
// 		'fa fa-info',
// 		'fa fa-info-circle',
// 		'fa fa-language',
// 		'fa fa-magic',
// 		'fa fa-microphone',
// 		'fa fa-microphone-slash',
// 		'fa fa-minus',
// 		'fa fa-minus-circle',
// 		'fa fa-minus-square',
// 		'fa fa-paste',
// 		'fa fa-pencil',
// 		'fa fa-plus',
// 		'fa fa-plus-circle',
// 		'fa fa-plus-square',
// 		'fa fa-qrcode',
// 		'fa fa-question',
// 		'fa fa-question-circle',
// 	],
// 	Maps: [
// 		'fa fa-location-arrow',
// 		'fa fa-map',
// 		'fa fa-map-marker',
// 		'fa fa-map-pin',
// 		'fa fa-map-signs',
// 		'fa fa-road',
// 	],
// 	'Payments & Shopping': [
// 		'fa fa-cart-arrow-down',
// 		'fa fa-cart-plus',
// 		'fa fa-cc-amex',
// 		'fa fa-cc-diners-club',
// 		'fa fa-cc-discover',
// 		'fa fa-cc-jcb',
// 		'fa fa-cc-mastercard',
// 		'fa fa-cc-paypal',
// 		'fa fa-cc-stripe',
// 		'fa fa-cc-visa',
// 		'fa fa-certificate',
// 		'fa fa-credit-card',
// 		'fa fa-gift',
// 		'fa fa-google-wallet',
// 		'fa fa-paypal',
// 		'fa fa-shopping-bag',
// 		'fa fa-shopping-cart',
// 	],
// 	Spinners: [
// 		'fa fa-asterisk',
// 		'fa fa-certificate',
// 		'fa fa-cog',
// 		'fa fa-compass',
// 		'fa fa-crosshairs',
// 		'fa fa-life-ring',
// 		'fa fa-spinner',
// 	],
// 	Status: [
// 		'fa fa-ban',
// 		'fa fa-battery-empty',
// 		'fa fa-battery-full',
// 		'fa fa-battery-half',
// 		'fa fa-battery-quarter',
// 		'fa fa-battery-three-quarters',
// 		'fa fa-bell',
// 		'fa fa-bell-slash',
// 		'fa fa-calendar',
// 		'fa fa-calendar-check-o',
// 		'fa fa-calendar-minus-o',
// 		'fa fa-calendar-plus-o',
// 		'fa fa-calendar-times-o',
// 		'fa fa-cart-arrow-down',
// 		'fa fa-cart-plus',
// 		'fa fa-exclamation',
// 		'fa fa-exclamation-circle',
// 		'fa fa-exclamation-triangle',
// 		'fa fa-eye',
// 		'fa fa-eye-slash',
// 		'fa fa-file',
// 		'fa fa-file-o',
// 		'fa fa-folder',
// 		'fa fa-folder-open',
// 		'fa fa-info',
// 		'fa fa-info-circle',
// 		'fa fa-lock',
// 		'fa fa-minus',
// 		'fa fa-minus-circle',
// 		'fa fa-minus-square',
// 		'fa fa-plus',
// 		'fa fa-plus-circle',
// 		'fa fa-plus-square',
// 		'fa fa-question',
// 		'fa fa-question-circle',
// 		'fa fa-shield',
// 		'fa fa-shopping-cart',
// 		'fa fa-sign-in',
// 		'fa fa-sign-out',
// 		'fa fa-thermometer-empty',
// 		'fa fa-thermometer-full',
// 		'fa fa-thermometer-half',
// 		'fa fa-thermometer-quarter',
// 		'fa fa-thermometer-three-quarters',
// 		'fa fa-thumbs-down',
// 		'fa fa-thumbs-up',
// 		'fa fa-toggle-off',
// 		'fa fa-toggle-on',
// 		'fa fa-unlock',
// 		'fa fa-unlock-alt',
// 	],
// 	'Users & People': [
// 		'fa fa-address-book',
// 		'fa fa-address-card',
// 		'fa fa-bed',
// 		'fa fa-blind',
// 		'fa fa-child',
// 		'fa fa-female',
// 		'fa fa-frown-o',
// 		'fa fa-id-badge',
// 		'fa fa-id-card',
// 		'fa fa-male',
// 		'fa fa-meh-o',
// 		'fa fa-power-off',
// 		'fa fa-smile-o',
// 		'fa fa-street-view',
// 		'fa fa-user',
// 		'fa fa-user-circle',
// 		'fa fa-user-md',
// 		'fa fa-user-plus',
// 		'fa fa-user-secret',
// 		'fa fa-user-times',
// 		'fa fa-users',
// 		'fa fa-wheelchair',
// 	],
// 	Vehicles: [
// 		'fa fa-ambulance',
// 		'fa fa-bicycle',
// 		'fa fa-bus',
// 		'fa fa-car',
// 		'fa fa-fighter-jet',
// 		'fa fa-motorcycle',
// 		'fa fa-paper-plane',
// 		'fa fa-plane',
// 		'fa fa-rocket',
// 		'fa fa-ship',
// 		'fa fa-shopping-cart',
// 		'fa fa-space-shuttle',
// 		'fa fa-subway',
// 		'fa fa-taxi',
// 		'fa fa-train',
// 		'fa fa-truck',
// 		'fa fa-wheelchair',
// 	],
// 	Writing: [
// 		'fa fa-archive',
// 		'fa fa-book',
// 		'fa fa-bookmark',
// 		'fa fa-edit',
// 		'fa fa-envelope',
// 		'fa fa-envelope-open',
// 		'fa fa-eraser',
// 		'fa fa-file',
// 		'fa fa-file-o',
// 		'fa fa-folder',
// 		'fa fa-folder-open',
// 		'fa fa-keyboard-o',
// 		'fa fa-newspaper-o',
// 		'fa fa-paper-plane',
// 		'fa fa-paperclip',
// 		'fa fa-paragraph',
// 		'fa fa-pencil',
// 		'fa fa-quote-left',
// 		'fa fa-quote-right',
// 		'fa fa-sticky-note',
// 	],
// };

// export default fontAwesome;

const fontAwesome = {
	Number: [
		"fa-solid fa-0 fa-fw",
		"fa-solid fa-1 fa-fw",
		"fa-solid fa-2 fa-fw",
		"fa-solid fa-3 fa-fw",
		"fa-solid fa-4 fa-fw",
		"fa-solid fa-5 fa-fw",
		"fa-solid fa-6 fa-fw",
		"fa-solid fa-7 fa-fw",
		"fa-solid fa-8 fa-fw",
		"fa-solid fa-9 fa-fw",
	],
	Accessibility: [
		"fab fa-accessible-icon",
		"fas fa-american-sign-language-interpreting",
		"fas fa-assistive-listening-systems",
		"fas fa-audio-description",
		"fas fa-blind",
		"fas fa-braille",
		"fas fa-closed-captioning",
		"far fa-closed-captioning",
		"fas fa-deaf",
		"fas fa-low-vision",
		"fas fa-phone-volume",
		"fas fa-question-circle",
		"far fa-question-circle",
		"fas fa-sign-language",
		"fas fa-tty",
		"fas fa-universal-access",
		"fas fa-wheelchair",
	],
	Social: [
		"fa-brands fa-facebook",
		"fa-brands fa-facebook-f",
		"fa-brands fa-square-facebook",
		"fa-brands fa-twitter",
		"fa-brands fa-square-twitter",
		"fa-brands fa-instagram",
		"fa-brands fa-square-instagram",
		"fa-brands fa-linkedin",
		"fa-brands fa-linkedin-in",
		"fa-brands fa-line",
		"fa-brands fa-github",
		"fa-brands fa-wordpress",
		"fa-brands fa-whatsapp",
		"fa-brands fa-behance",
		"fa-brands fa-free-code-camp",
		"fa-solid fa-square-share-nodes",
		"fa-brands fa-square-google-plus",
		"fa-brands fa-google-plus-g",
		"fa-brands fa-square-gitlab",
		"fa-brands fa-pinterest-p",
	],
	Arrows: [
		"fas fa-angle-double-down",
		"fas fa-angle-double-left",
		"fas fa-angle-double-right",
		"fas fa-angle-double-up",
		"fas fa-angle-down",
		"fas fa-angle-left",
		"fas fa-angle-right",
		"fas fa-angle-up",
		"fas fa-arrow-alt-circle-down",
		"far fa-arrow-alt-circle-down",
		"fas fa-arrow-alt-circle-left",
		"far fa-arrow-alt-circle-left",
		"fas fa-arrow-alt-circle-right",
		"far fa-arrow-alt-circle-right",
		"fas fa-arrow-alt-circle-up",
		"far fa-arrow-alt-circle-up",
		"fas fa-arrow-circle-down",
		"fas fa-arrow-circle-left",
		"fas fa-arrow-circle-right",
		"fas fa-arrow-circle-up",
		"fas fa-arrow-down",
		"fas fa-arrow-left",
		"fas fa-arrow-right",
		"fas fa-arrow-up",
		"fas fa-arrows-alt",
		"fas fa-arrows-alt-h",
		"fas fa-arrows-alt-v",
		"fas fa-caret-down",
		"fas fa-caret-left",
		"fas fa-caret-right",
		"fas fa-caret-square-down",
		"far fa-caret-square-down",
		"fas fa-caret-square-left",
		"far fa-caret-square-left",
		"fas fa-caret-square-right",
		"far fa-caret-square-right",
		"fas fa-caret-square-up",
		"far fa-caret-square-up",
		"fas fa-caret-up",
		"fas fa-cart-arrow-down",
		"fas fa-chart-line",
		"fas fa-chevron-circle-down",
		"fas fa-chevron-circle-left",
		"fas fa-chevron-circle-right",
		"fas fa-chevron-circle-up",
		"fas fa-chevron-down",
		"fas fa-chevron-left",
		"fas fa-chevron-right",
		"fas fa-chevron-up",
		"fas fa-cloud-download-alt",
		"fas fa-cloud-upload-alt",
		"fas fa-download",
		"fas fa-exchange-alt",
		"fas fa-expand-arrows-alt",
		"fas fa-external-link-alt",
		"fas fa-external-link-square-alt",
		"fas fa-hand-point-down",
		"far fa-hand-point-down",
		"fas fa-hand-point-left",
		"far fa-hand-point-left",
		"fas fa-hand-point-right",
		"far fa-hand-point-right",
		"fas fa-hand-point-up",
		"far fa-hand-point-up",
		"fas fa-hand-pointer",
		"far fa-hand-pointer",
		"fas fa-history",
		"fas fa-level-down-alt",
		"fas fa-level-up-alt",
		"fas fa-location-arrow",
		"fas fa-long-arrow-alt-down",
		"fas fa-long-arrow-alt-left",
		"fas fa-long-arrow-alt-right",
		"fas fa-long-arrow-alt-up",
		"fas fa-mouse-pointer",
		"fas fa-play",
		"fas fa-random",
		"fas fa-recycle",
		"fas fa-redo",
		"fas fa-redo-alt",
		"fas fa-reply",
		"fas fa-reply-all",
		"fas fa-retweet",
		"fas fa-share",
		"fas fa-share-square",
		"far fa-share-square",
		"fas fa-sign-in-alt",
		"fas fa-sign-out-alt",
		"fas fa-sort",
		"fas fa-sort-alpha-down",
		"fas fa-sort-alpha-up",
		"fas fa-sort-amount-down",
		"fas fa-sort-amount-up",
		"fas fa-sort-down",
		"fas fa-sort-numeric-down",
		"fas fa-sort-numeric-up",
		"fas fa-sort-up",
		"fas fa-sync",
		"fas fa-sync-alt",
		"fas fa-text-height",
		"fas fa-text-width",
		"fas fa-undo",
		"fas fa-undo-alt",
		"fas fa-upload",
	],
	"Audio & Video": [
		"fas fa-audio-description",
		"fas fa-backward",
		"fas fa-circle",
		"far fa-circle",
		"fas fa-closed-captioning",
		"far fa-closed-captioning",
		"fas fa-compress",
		"fas fa-eject",
		"fas fa-expand",
		"fas fa-expand-arrows-alt",
		"fas fa-fast-backward",
		"fas fa-fast-forward",
		"fas fa-file-audio",
		"far fa-file-audio",
		"fas fa-file-video",
		"far fa-file-video",
		"fas fa-film",
		"fas fa-forward",
		"fas fa-headphones",
		"fas fa-microphone",
		"fas fa-microphone-slash",
		"fas fa-music",
		"fas fa-pause",
		"fas fa-pause-circle",
		"far fa-pause-circle",
		"fas fa-phone-volume",
		"fas fa-play",
		"fas fa-play-circle",
		"far fa-play-circle",
		"fas fa-podcast",
		"fas fa-random",
		"fas fa-redo",
		"fas fa-redo-alt",
		"fas fa-rss",
		"fas fa-rss-square",
		"fas fa-step-backward",
		"fas fa-step-forward",
		"fas fa-stop",
		"fas fa-stop-circle",
		"far fa-stop-circle",
		"fas fa-sync",
		"fas fa-sync-alt",
		"fas fa-undo",
		"fas fa-undo-alt",
		"fas fa-video",
		"fas fa-volume-down",
		"fas fa-volume-off",
		"fas fa-volume-up",
		"fab fa-youtube",
	],
	Business: [
		"fas fa-address-book",
		"far fa-address-book",
		"fas fa-address-card",
		"far fa-address-card",
		"fas fa-archive",
		"fas fa-balance-scale",
		"fas fa-birthday-cake",
		"fas fa-book",
		"fas fa-briefcase",
		"fas fa-building",
		"far fa-building",
		"fas fa-bullhorn",
		"fas fa-bullseye",
		"fas fa-calculator",
		"fas fa-calendar",
		"far fa-calendar",
		"fas fa-calendar-alt",
		"far fa-calendar-alt",
		"fas fa-certificate",
		"fas fa-chart-area",
		"fas fa-chart-bar",
		"far fa-chart-bar",
		"fas fa-chart-line",
		"fas fa-chart-pie",
		"fas fa-clipboard",
		"far fa-clipboard",
		"fas fa-coffee",
		"fas fa-columns",
		"fas fa-compass",
		"far fa-compass",
		"fas fa-copy",
		"far fa-copy",
		"fas fa-copyright",
		"far fa-copyright",
		"fas fa-cut",
		"fas fa-edit",
		"far fa-edit",
		"fas fa-envelope",
		"far fa-envelope",
		"fas fa-envelope-open",
		"far fa-envelope-open",
		"fas fa-envelope-square",
		"fas fa-eraser",
		"fas fa-fax",
		"fas fa-file",
		"far fa-file",
		"fas fa-file-alt",
		"far fa-file-alt",
		"fas fa-folder",
		"far fa-folder",
		"fas fa-folder-open",
		"far fa-folder-open",
		"fas fa-globe",
		"fas fa-industry",
		"fas fa-paperclip",
		"fas fa-paste",
		"fas fa-pen-square",
		"fas fa-pencil-alt",
		"fas fa-percent",
		"fas fa-phone",
		"fas fa-phone-square",
		"fas fa-phone-volume",
		"fas fa-registered",
		"far fa-registered",
		"fas fa-save",
		"far fa-save",
		"fas fa-sitemap",
		"fas fa-sticky-note",
		"far fa-sticky-note",
		"fas fa-suitcase",
		"fas fa-table",
		"fas fa-tag",
		"fas fa-tags",
		"fas fa-tasks",
		"fas fa-thumbtack",
		"fas fa-trademark",
	],
	Chess: [
		"fas fa-chess",
		"fas fa-chess-bishop",
		"fas fa-chess-board",
		"fas fa-chess-king",
		"fas fa-chess-knight",
		"fas fa-chess-pawn",
		"fas fa-chess-queen",
		"fas fa-chess-rook",
		"fas fa-square-full",
	],
	Code: [
		"fas fa-archive",
		"fas fa-barcode",
		"fas fa-bath",
		"fas fa-bug",
		"fas fa-code",
		"fas fa-code-branch",
		"fas fa-coffee",
		"fas fa-file",
		"far fa-file",
		"fas fa-file-alt",
		"far fa-file-alt",
		"fas fa-file-code",
		"far fa-file-code",
		"fas fa-filter",
		"fas fa-fire-extinguisher",
		"fas fa-folder",
		"far fa-folder",
		"fas fa-folder-open",
		"far fa-folder-open",
		"fas fa-keyboard",
		"far fa-keyboard",
		"fas fa-microchip",
		"fas fa-qrcode",
		"fas fa-shield-alt",
		"fas fa-sitemap",
		"fas fa-terminal",
		"fas fa-user-secret",
		"fas fa-window-close",
		"far fa-window-close",
		"fas fa-window-maximize",
		"far fa-window-maximize",
		"fas fa-window-minimize",
		"far fa-window-minimize",
		"fas fa-window-restore",
		"far fa-window-restore",
	],
	Communication: [
		"fas fa-address-book",
		"far fa-address-book",
		"fas fa-address-card",
		"far fa-address-card",
		"fas fa-american-sign-language-interpreting",
		"fas fa-assistive-listening-systems",
		"fas fa-at",
		"fas fa-bell",
		"far fa-bell",
		"fas fa-bell-slash",
		"far fa-bell-slash",
		"fab fa-bluetooth",
		"fab fa-bluetooth-b",
		"fas fa-bullhorn",
		"fas fa-comment",
		"far fa-comment",
		"fas fa-comment-alt",
		"far fa-comment-alt",
		"fas fa-comments",
		"far fa-comments",
		"fas fa-envelope",
		"far fa-envelope",
		"fas fa-envelope-open",
		"far fa-envelope-open",
		"fas fa-envelope-square",
		"fas fa-fax",
		"fas fa-inbox",
		"fas fa-language",
		"fas fa-microphone",
		"fas fa-microphone-slash",
		"fas fa-mobile",
		"fas fa-mobile-alt",
		"fas fa-paper-plane",
		"far fa-paper-plane",
		"fas fa-phone",
		"fas fa-phone-square",
		"fas fa-phone-volume",
		"fas fa-rss",
		"fas fa-rss-square",
		"fas fa-tty",
		"fas fa-wifi",
	],
	Computers: [
		"fas fa-desktop",
		"fas fa-download",
		"fas fa-hdd",
		"far fa-hdd",
		"fas fa-headphones",
		"fas fa-keyboard",
		"far fa-keyboard",
		"fas fa-laptop",
		"fas fa-microchip",
		"fas fa-mobile",
		"fas fa-mobile-alt",
		"fas fa-plug",
		"fas fa-power-off",
		"fas fa-print",
		"fas fa-save",
		"far fa-save",
		"fas fa-server",
		"fas fa-tablet",
		"fas fa-tablet-alt",
		"fas fa-tv",
		"fas fa-upload",
	],
	Currency: [
		"fab fa-bitcoin",
		"fab fa-btc",
		"fas fa-dollar-sign",
		"fas fa-euro-sign",
		"fab fa-gg",
		"fab fa-gg-circle",
		"fas fa-lira-sign",
		"fas fa-money-bill-alt",
		"far fa-money-bill-alt",
		"fas fa-pound-sign",
		"fas fa-ruble-sign",
		"fas fa-rupee-sign",
		"fas fa-shekel-sign",
		"fas fa-won-sign",
		"fas fa-yen-sign",
	],
	"Date & Time": [
		"fas fa-bell",
		"far fa-bell",
		"fas fa-bell-slash",
		"far fa-bell-slash",
		"fas fa-calendar",
		"far fa-calendar",
		"fas fa-calendar-alt",
		"far fa-calendar-alt",
		"fas fa-calendar-check",
		"far fa-calendar-check",
		"fas fa-calendar-minus",
		"far fa-calendar-minus",
		"fas fa-calendar-plus",
		"far fa-calendar-plus",
		"fas fa-calendar-times",
		"far fa-calendar-times",
		"fas fa-clock",
		"far fa-clock",
		"fas fa-hourglass",
		"far fa-hourglass",
		"fas fa-hourglass-end",
		"fas fa-hourglass-half",
		"fas fa-hourglass-start",
		"fas fa-stopwatch",
	],
	Design: [
		"fas fa-adjust",
		"fas fa-clone",
		"far fa-clone",
		"fas fa-copy",
		"far fa-copy",
		"fas fa-crop",
		"fas fa-crosshairs",
		"fas fa-cut",
		"fas fa-edit",
		"far fa-edit",
		"fas fa-eraser",
		"fas fa-eye",
		"fas fa-eye-dropper",
		"fas fa-eye-slash",
		"far fa-eye-slash",
		"fas fa-object-group",
		"far fa-object-group",
		"fas fa-object-ungroup",
		"far fa-object-ungroup",
		"fas fa-paint-brush",
		"fas fa-paste",
		"fas fa-pencil-alt",
		"fas fa-save",
		"far fa-save",
		"fas fa-tint",
	],
	Editors: [
		"fas fa-align-center",
		"fas fa-align-justify",
		"fas fa-align-left",
		"fas fa-align-right",
		"fas fa-bold",
		"fas fa-clipboard",
		"far fa-clipboard",
		"fas fa-clone",
		"far fa-clone",
		"fas fa-columns",
		"fas fa-copy",
		"far fa-copy",
		"fas fa-cut",
		"fas fa-edit",
		"far fa-edit",
		"fas fa-eraser",
		"fas fa-file",
		"far fa-file",
		"fas fa-file-alt",
		"far fa-file-alt",
		"fas fa-font",
		"fas fa-heading",
		"fas fa-i-cursor",
		"fas fa-indent",
		"fas fa-italic",
		"fas fa-link",
		"fas fa-list",
		"fas fa-list-alt",
		"far fa-list-alt",
		"fas fa-list-ol",
		"fas fa-list-ul",
		"fas fa-outdent",
		"fas fa-paper-plane",
		"far fa-paper-plane",
		"fas fa-paperclip",
		"fas fa-paragraph",
		"fas fa-paste",
		"fas fa-pencil-alt",
		"fas fa-print",
		"fas fa-quote-left",
		"fas fa-quote-right",
		"fas fa-redo",
		"fas fa-redo-alt",
		"fas fa-reply",
		"fas fa-reply-all",
		"fas fa-share",
		"fas fa-strikethrough",
		"fas fa-subscript",
		"fas fa-superscript",
		"fas fa-sync",
		"fas fa-sync-alt",
		"fas fa-table",
		"fas fa-tasks",
		"fas fa-text-height",
		"fas fa-text-width",
		"fas fa-th",
		"fas fa-th-large",
		"fas fa-th-list",
		"fas fa-trash",
		"fas fa-trash-alt",
		"far fa-trash-alt",
		"fas fa-underline",
		"fas fa-undo",
		"fas fa-undo-alt",
		"fas fa-unlink",
	],
	Files: [
		"fas fa-archive",
		"fas fa-clone",
		"far fa-clone",
		"fas fa-copy",
		"far fa-copy",
		"fas fa-cut",
		"fas fa-file",
		"far fa-file",
		"fas fa-file-alt",
		"far fa-file-alt",
		"fas fa-file-archive",
		"far fa-file-archive",
		"fas fa-file-audio",
		"far fa-file-audio",
		"fas fa-file-code",
		"far fa-file-code",
		"fas fa-file-excel",
		"far fa-file-excel",
		"fas fa-file-image",
		"far fa-file-image",
		"fas fa-file-pdf",
		"far fa-file-pdf",
		"fas fa-file-powerpoint",
		"far fa-file-powerpoint",
		"fas fa-file-video",
		"far fa-file-video",
		"fas fa-file-word",
		"far fa-file-word",
		"fas fa-folder",
		"far fa-folder",
		"fas fa-folder-open",
		"far fa-folder-open",
		"fas fa-paste",
		"fas fa-save",
		"far fa-save",
		"fas fa-sticky-note",
		"far fa-sticky-note",
	],
	Genders: [
		"fas fa-genderless",
		"fas fa-mars",
		"fas fa-mars-double",
		"fas fa-mars-stroke",
		"fas fa-mars-stroke-h",
		"fas fa-mars-stroke-v",
		"fas fa-mercury",
		"fas fa-neuter",
		"fas fa-transgender",
		"fas fa-transgender-alt",
		"fas fa-venus",
		"fas fa-venus-double",
		"fas fa-venus-mars",
	],
	Hands: [
		"fas fa-hand-lizard",
		"far fa-hand-lizard",
		"fas fa-hand-paper",
		"far fa-hand-paper",
		"fas fa-hand-peace",
		"far fa-hand-peace",
		"fas fa-hand-point-down",
		"far fa-hand-point-down",
		"fas fa-hand-point-left",
		"far fa-hand-point-left",
		"fas fa-hand-point-right",
		"far fa-hand-point-right",
		"fas fa-hand-point-up",
		"far fa-hand-point-up",
		"fas fa-hand-pointer",
		"far fa-hand-pointer",
		"fas fa-hand-rock",
		"far fa-hand-rock",
		"fas fa-hand-scissors",
		"far fa-hand-scissors",
		"fas fa-hand-spock",
		"far fa-hand-spock",
		"fas fa-handshake",
		"far fa-handshake",
		"fas fa-thumbs-down",
		"far fa-thumbs-down",
		"fas fa-thumbs-up",
		"far fa-thumbs-up",
	],
	Health: [
		"fab fa-accessible-icon",
		"fas fa-ambulance",
		"fas fa-h-square",
		"fas fa-heart",
		"far fa-heart",
		"fas fa-heartbeat",
		"fas fa-hospital",
		"far fa-hospital",
		"fas fa-medkit",
		"fas fa-plus-square",
		"far fa-plus-square",
		"fas fa-stethoscope",
		"fas fa-user-md",
		"fas fa-wheelchair",
	],
	Images: [
		"fas fa-adjust",
		"fas fa-bolt",
		"fas fa-camera",
		"fas fa-camera-retro",
		"fas fa-clone",
		"far fa-clone",
		"fas fa-compress",
		"fas fa-expand",
		"fas fa-eye",
		"fas fa-eye-dropper",
		"fas fa-eye-slash",
		"far fa-eye-slash",
		"fas fa-file-image",
		"far fa-file-image",
		"fas fa-film",
		"fas fa-id-badge",
		"far fa-id-badge",
		"fas fa-id-card",
		"far fa-id-card",
		"fas fa-image",
		"far fa-image",
		"fas fa-images",
		"far fa-images",
		"fas fa-sliders-h",
		"fas fa-tint",
	],
	Interfaces: [
		"fas fa-ban",
		"fas fa-barcode",
		"fas fa-bars",
		"fas fa-beer",
		"fas fa-bell",
		"far fa-bell",
		"fas fa-bell-slash",
		"far fa-bell-slash",
		"fas fa-bug",
		"fas fa-bullhorn",
		"fas fa-bullseye",
		"fas fa-calculator",
		"fas fa-calendar",
		"far fa-calendar",
		"fas fa-calendar-alt",
		"far fa-calendar-alt",
		"fas fa-calendar-check",
		"far fa-calendar-check",
		"fas fa-calendar-minus",
		"far fa-calendar-minus",
		"fas fa-calendar-plus",
		"far fa-calendar-plus",
		"fas fa-calendar-times",
		"far fa-calendar-times",
		"fas fa-certificate",
		"fas fa-check",
		"fas fa-check-circle",
		"far fa-check-circle",
		"fas fa-check-square",
		"far fa-check-square",
		"fas fa-circle",
		"far fa-circle",
		"fas fa-clipboard",
		"far fa-clipboard",
		"fas fa-clone",
		"far fa-clone",
		"fas fa-cloud",
		"fas fa-cloud-download-alt",
		"fas fa-cloud-upload-alt",
		"fas fa-coffee",
		"fas fa-cog",
		"fas fa-cogs",
		"fas fa-copy",
		"far fa-copy",
		"fas fa-cut",
		"fas fa-database",
		"fas fa-dot-circle",
		"far fa-dot-circle",
		"fas fa-download",
		"fas fa-edit",
		"far fa-edit",
		"fas fa-ellipsis-h",
		"fas fa-ellipsis-v",
		"fas fa-envelope",
		"far fa-envelope",
		"fas fa-envelope-open",
		"far fa-envelope-open",
		"fas fa-eraser",
		"fas fa-exclamation",
		"fas fa-exclamation-circle",
		"fas fa-exclamation-triangle",
		"fas fa-external-link-alt",
		"fas fa-external-link-square-alt",
		"fas fa-eye",
		"fas fa-eye-slash",
		"far fa-eye-slash",
		"fas fa-file",
		"far fa-file",
		"fas fa-file-alt",
		"far fa-file-alt",
		"fas fa-filter",
		"fas fa-flag",
		"far fa-flag",
		"fas fa-flag-checkered",
		"fas fa-folder",
		"far fa-folder",
		"fas fa-folder-open",
		"far fa-folder-open",
		"fas fa-frown",
		"far fa-frown",
		"fas fa-hashtag",
		"fas fa-heart",
		"far fa-heart",
		"fas fa-history",
		"fas fa-home",
		"fas fa-i-cursor",
		"fas fa-info",
		"fas fa-info-circle",
		"fas fa-language",
		"fas fa-magic",
		"fas fa-meh",
		"far fa-meh",
		"fas fa-microphone",
		"fas fa-microphone-slash",
		"fas fa-minus",
		"fas fa-minus-circle",
		"fas fa-minus-square",
		"far fa-minus-square",
		"fas fa-paste",
		"fas fa-pencil-alt",
		"fas fa-plus",
		"fas fa-plus-circle",
		"fas fa-plus-square",
		"far fa-plus-square",
		"fas fa-qrcode",
		"fas fa-question",
		"fas fa-question-circle",
		"far fa-question-circle",
	],
	Maps: [
		"fas fa-ambulance",
		"fas fa-anchor",
		"fas fa-balance-scale",
		"fas fa-bath",
		"fas fa-bed",
		"fas fa-beer",
		"fas fa-bell",
		"far fa-bell",
		"fas fa-bell-slash",
		"far fa-bell-slash",
		"fas fa-bicycle",
		"fas fa-binoculars",
		"fas fa-birthday-cake",
		"fas fa-blind",
		"fas fa-bomb",
		"fas fa-book",
		"fas fa-bookmark",
		"far fa-bookmark",
		"fas fa-briefcase",
		"fas fa-building",
		"far fa-building",
		"fas fa-car",
		"fas fa-coffee",
		"fas fa-crosshairs",
		"fas fa-dollar-sign",
		"fas fa-eye",
		"fas fa-eye-slash",
		"far fa-eye-slash",
		"fas fa-fighter-jet",
		"fas fa-fire",
		"fas fa-fire-extinguisher",
		"fas fa-flag",
		"far fa-flag",
		"fas fa-flag-checkered",
		"fas fa-flask",
		"fas fa-gamepad",
		"fas fa-gavel",
		"fas fa-gift",
		"fas fa-glass-martini",
		"fas fa-globe",
		"fas fa-graduation-cap",
		"fas fa-h-square",
		"fas fa-heart",
		"far fa-heart",
		"fas fa-heartbeat",
		"fas fa-home",
		"fas fa-hospital",
		"far fa-hospital",
		"fas fa-image",
		"far fa-image",
		"fas fa-images",
		"far fa-images",
		"fas fa-industry",
		"fas fa-info",
		"fas fa-info-circle",
		"fas fa-key",
		"fas fa-leaf",
		"fas fa-lemon",
		"far fa-lemon",
		"fas fa-life-ring",
		"far fa-life-ring",
		"fas fa-lightbulb",
		"far fa-lightbulb",
		"fas fa-location-arrow",
		"fas fa-low-vision",
		"fas fa-magnet",
		"fas fa-male",
		"fas fa-map",
		"far fa-map",
		"fas fa-map-marker",
		"fas fa-map-marker-alt",
		"fas fa-map-pin",
		"fas fa-map-signs",
		"fas fa-medkit",
		"fas fa-money-bill-alt",
		"far fa-money-bill-alt",
		"fas fa-motorcycle",
		"fas fa-music",
		"fas fa-newspaper",
		"far fa-newspaper",
		"fas fa-paw",
		"fas fa-phone",
		"fas fa-phone-square",
		"fas fa-phone-volume",
		"fas fa-plane",
		"fa-solid fa-plane-departure",
		"fas fa-plug",
		"fas fa-plus",
		"fas fa-plus-square",
		"far fa-plus-square",
		"fas fa-print",
		"fas fa-recycle",
		"fas fa-road",
		"fas fa-rocket",
		"fas fa-search",
		"fas fa-search-minus",
		"fas fa-search-plus",
		"fas fa-ship",
		"fas fa-shopping-bag",
		"fas fa-shopping-basket",
		"fas fa-shopping-cart",
		"fas fa-shower",
		"fas fa-street-view",
		"fas fa-subway",
		"fas fa-suitcase",
		"fas fa-tag",
		"fas fa-tags",
		"fas fa-taxi",
		"fas fa-thumbtack",
	],
	Objects: [
		"fas fa-ambulance",
		"fas fa-anchor",
		"fas fa-archive",
		"fas fa-balance-scale",
		"fas fa-bath",
		"fas fa-bed",
		"fas fa-beer",
		"fas fa-bell",
		"far fa-bell",
		"fas fa-bicycle",
		"fas fa-binoculars",
		"fas fa-birthday-cake",
		"fas fa-bomb",
		"fas fa-book",
		"fas fa-bookmark",
		"far fa-bookmark",
		"fas fa-briefcase",
		"fas fa-bug",
		"fas fa-building",
		"far fa-building",
		"fas fa-bullhorn",
		"fas fa-bullseye",
		"fas fa-bus",
		"fas fa-calculator",
		"fas fa-calendar",
		"far fa-calendar",
		"fas fa-calendar-alt",
		"far fa-calendar-alt",
		"fas fa-camera",
		"fas fa-camera-retro",
		"fas fa-car",
		"fas fa-clipboard",
		"far fa-clipboard",
		"fas fa-cloud",
		"fas fa-coffee",
		"fas fa-cog",
		"fas fa-cogs",
		"fas fa-compass",
		"far fa-compass",
		"fas fa-copy",
		"far fa-copy",
		"fas fa-cube",
		"fas fa-cubes",
		"fas fa-cut",
		"fas fa-envelope",
		"far fa-envelope",
		"fas fa-envelope-open",
		"far fa-envelope-open",
		"fas fa-eraser",
		"fas fa-eye",
		"fas fa-eye-dropper",
		"fas fa-fax",
		"fas fa-fighter-jet",
		"fas fa-file",
		"far fa-file",
		"fas fa-file-alt",
		"far fa-file-alt",
		"fas fa-film",
		"fas fa-fire",
		"fas fa-fire-extinguisher",
		"fas fa-flag",
		"far fa-flag",
		"fas fa-flag-checkered",
		"fas fa-flask",
		"fas fa-futbol",
		"far fa-futbol",
		"fas fa-gamepad",
		"fas fa-gavel",
		"fas fa-gem",
		"far fa-gem",
		"fas fa-gift",
		"fas fa-glass-martini",
		"fas fa-globe",
		"fas fa-graduation-cap",
		"fas fa-hdd",
		"far fa-hdd",
		"fas fa-headphones",
		"fas fa-heart",
		"far fa-heart",
		"fas fa-home",
		"fas fa-hospital",
		"far fa-hospital",
		"fas fa-hourglass",
		"far fa-hourglass",
		"fas fa-image",
		"far fa-image",
		"fas fa-images",
		"far fa-images",
		"fas fa-industry",
		"fas fa-key",
		"fas fa-keyboard",
		"far fa-keyboard",
		"fas fa-laptop",
		"fas fa-leaf",
		"fas fa-lemon",
		"far fa-lemon",
		"fas fa-life-ring",
		"far fa-life-ring",
		"fas fa-lightbulb",
		"far fa-lightbulb",
		"fas fa-lock",
		"fas fa-lock-open",
		"fas fa-magic",
		"fas fa-magnet",
		"fas fa-map",
		"far fa-map",
		"fas fa-map-marker",
		"fas fa-map-marker-alt",
	],
	"Payments & Shopping": [
		"fab fa-amazon-pay",
		"fab fa-apple-pay",
		"fas fa-bell",
		"far fa-bell",
		"fas fa-bookmark",
		"far fa-bookmark",
		"fas fa-bullhorn",
		"fas fa-camera",
		"fas fa-camera-retro",
		"fas fa-cart-arrow-down",
		"fas fa-cart-plus",
		"fab fa-cc-amazon-pay",
		"fab fa-cc-amex",
		"fab fa-cc-apple-pay",
		"fab fa-cc-diners-club",
		"fab fa-cc-discover",
		"fab fa-cc-jcb",
		"fab fa-cc-mastercard",
		"fab fa-cc-paypal",
		"fab fa-cc-stripe",
		"fab fa-cc-visa",
		"fas fa-certificate",
		"fas fa-credit-card",
		"far fa-credit-card",
		"fab fa-ethereum",
		"fas fa-gem",
		"far fa-gem",
		"fas fa-gift",
		"fab fa-google-wallet",
		"fas fa-handshake",
		"far fa-handshake",
		"fas fa-heart",
		"far fa-heart",
		"fas fa-key",
		"fab fa-paypal",
		"fas fa-shopping-bag",
		"fas fa-shopping-basket",
		"fas fa-shopping-cart",
		"fas fa-star",
		"far fa-star",
		"fab fa-stripe",
		"fab fa-stripe-s",
		"fas fa-tag",
		"fas fa-tags",
		"fas fa-thumbs-down",
		"far fa-thumbs-down",
		"fas fa-thumbs-up",
		"far fa-thumbs-up",
		"fas fa-trophy",
	],
	Shapes: [
		"fas fa-bookmark",
		"far fa-bookmark",
		"fas fa-calendar",
		"far fa-calendar",
		"fas fa-certificate",
		"fas fa-circle",
		"far fa-circle",
		"fas fa-cloud",
		"fas fa-comment",
		"far fa-comment",
		"fas fa-file",
		"far fa-file",
		"fas fa-folder",
		"far fa-folder",
		"fas fa-heart",
		"far fa-heart",
		"fas fa-map-marker",
		"fas fa-play",
		"fas fa-square",
		"far fa-square",
		"fas fa-star",
		"far fa-star",
	],
	Spinners: [
		"fas fa-asterisk",
		"fas fa-certificate",
		"fas fa-circle-notch",
		"fas fa-cog",
		"fas fa-compass",
		"far fa-compass",
		"fas fa-crosshairs",
		"fas fa-life-ring",
		"far fa-life-ring",
		"fas fa-snowflake",
		"far fa-snowflake",
		"fas fa-spinner",
		"fas fa-sun",
		"far fa-sun",
		"fas fa-sync",
	],
	Sports: [
		"fas fa-baseball-ball",
		"fas fa-basketball-ball",
		"fas fa-bowling-ball",
		"fas fa-football-ball",
		"fas fa-futbol",
		"far fa-futbol",
		"fas fa-golf-ball",
		"fas fa-hockey-puck",
		"fas fa-quidditch",
		"fas fa-table-tennis",
		"fas fa-volleyball-ball",
	],
	Status: [
		"fas fa-ban",
		"fas fa-battery-empty",
		"fas fa-battery-full",
		"fas fa-battery-half",
		"fas fa-battery-quarter",
		"fas fa-battery-three-quarters",
		"fas fa-bell",
		"far fa-bell",
		"fas fa-bell-slash",
		"far fa-bell-slash",
		"fas fa-calendar",
		"far fa-calendar",
		"fas fa-calendar-alt",
		"far fa-calendar-alt",
		"fas fa-calendar-check",
		"far fa-calendar-check",
		"fas fa-calendar-minus",
		"far fa-calendar-minus",
		"fas fa-calendar-plus",
		"far fa-calendar-plus",
		"fas fa-calendar-times",
		"far fa-calendar-times",
		"fas fa-cart-arrow-down",
		"fas fa-cart-plus",
		"fas fa-exclamation",
		"fas fa-exclamation-circle",
		"fas fa-exclamation-triangle",
		"fas fa-eye",
		"fas fa-eye-slash",
		"far fa-eye-slash",
		"fas fa-file",
		"far fa-file",
		"fas fa-file-alt",
		"far fa-file-alt",
		"fas fa-folder",
		"far fa-folder",
		"fas fa-folder-open",
		"far fa-folder-open",
		"fas fa-info",
		"fas fa-info-circle",
		"fas fa-lock",
		"fas fa-lock-open",
		"fas fa-minus",
		"fas fa-minus-circle",
		"fas fa-minus-square",
		"far fa-minus-square",
		"fas fa-plus",
		"fas fa-plus-circle",
		"fas fa-plus-square",
		"far fa-plus-square",
		"fas fa-question",
		"fas fa-question-circle",
		"far fa-question-circle",
		"fas fa-shield-alt",
		"fas fa-shopping-cart",
		"fas fa-sign-in-alt",
		"fas fa-sign-out-alt",
		"fas fa-thermometer-empty",
		"fas fa-thermometer-full",
		"fas fa-thermometer-half",
		"fas fa-thermometer-quarter",
		"fas fa-thermometer-three-quarters",
		"fas fa-thumbs-down",
		"far fa-thumbs-down",
		"fas fa-thumbs-up",
		"far fa-thumbs-up",
		"fas fa-toggle-off",
		"fas fa-toggle-on",
		"fas fa-unlock",
		"fas fa-unlock-alt",
	],
	"Users & People": [
		"fab fa-accessible-icon",
		"fas fa-address-book",
		"far fa-address-book",
		"fas fa-address-card",
		"far fa-address-card",
		"fas fa-bed",
		"fas fa-blind",
		"fas fa-child",
		"fas fa-female",
		"fas fa-frown",
		"far fa-frown",
		"fas fa-id-badge",
		"far fa-id-badge",
		"fas fa-id-card",
		"far fa-id-card",
		"fas fa-male",
		"fas fa-meh",
		"far fa-meh",
		"fas fa-power-off",
		"fas fa-smile",
		"far fa-smile",
		"fas fa-street-view",
		"fas fa-user",
		"far fa-user",
		"fas fa-user-circle",
		"far fa-user-circle",
		"fas fa-user-md",
		"fas fa-user-plus",
		"fas fa-user-secret",
		"fas fa-user-times",
		"fas fa-users",
		"fas fa-wheelchair",
	],
	Vehicles: [
		"fab fa-accessible-icon",
		"fas fa-ambulance",
		"fas fa-bicycle",
		"fas fa-bus",
		"fas fa-car",
		"fas fa-fighter-jet",
		"fas fa-motorcycle",
		"fas fa-paper-plane",
		"far fa-paper-plane",
		"fas fa-plane",
		"fas fa-rocket",
		"fas fa-ship",
		"fas fa-shopping-cart",
		"fas fa-space-shuttle",
		"fas fa-subway",
		"fas fa-taxi",
		"fas fa-train",
		"fas fa-truck",
		"fas fa-wheelchair",
	],
	Writing: [
		"fas fa-archive",
		"fas fa-book",
		"fas fa-bookmark",
		"far fa-bookmark",
		"fas fa-edit",
		"far fa-edit",
		"fas fa-envelope",
		"far fa-envelope",
		"fas fa-envelope-open",
		"far fa-envelope-open",
		"fas fa-eraser",
		"fas fa-file",
		"far fa-file",
		"fas fa-file-alt",
		"far fa-file-alt",
		"fas fa-folder",
		"far fa-folder",
		"fas fa-folder-open",
		"far fa-folder-open",
		"fas fa-keyboard",
		"far fa-keyboard",
		"fas fa-newspaper",
		"far fa-newspaper",
		"fas fa-paper-plane",
		"far fa-paper-plane",
		"fas fa-paperclip",
		"fas fa-paragraph",
		"fas fa-pen-square",
		"fas fa-pencil-alt",
		"fas fa-quote-left",
		"fas fa-quote-right",
		"fas fa-sticky-note",
		"far fa-sticky-note",
		"fas fa-thumbtack",
	],
};

export default fontAwesome;
